services:
  # Builder - генерирует CBMA14.json из data.json
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
    command: |
      bash -c "
        python /app/build_index.py
        echo 'Initial build complete. Sleeping...'
        while true; do
          sleep 3600
          python /app/build_index.py
          echo 'Updated at $(date)'
        done
      "
    restart: unless-stopped

  # UDF сервер на Flask
  udf:
    build:
      context: .
      dockerfile: Dockerfile.udf
    volumes:
      - ./data:/data:ro
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - COINGLASS_API_KEY=${COINGLASS_API_KEY}
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 30 src.udf.server:app
    restart: unless-stopped
    depends_on:
      - builder

  # Nginx - проксирование и кэширование
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/chart:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - udf

networks:
  default:
    name: udf_network 