name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Ruff
        run: poetry run ruff app_rank tests cli.py
      - name: MyPy
        run: poetry run mypy app_rank
      - name: PyTest
        run: poetry run pytest -q 