name: 🔄 Обновление Композитного Индекса

# Запуск каждые 6 часов и при пуше в main
on:
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Ручной запуск

jobs:
  update-index:
    name: 📊 Обновить композитный индекс
    runs-on: ubuntu-latest
    
    steps:
    - name: ✅ Checkout кода
      uses: actions/checkout@v4
      
    - name: 🐍 Настройка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: 📦 Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: ⚙️ Настройка TA-Lib (если нужно)
      run: |
        # TA-Lib часто требует дополнительной установки
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Можно также использовать без TA-Lib, заменив на pandas rolling
        
    - name: 📊 Обновление индекса
      env:
        APP_RANKINGS_API_KEY: ${{ secrets.APP_RANKINGS_API_KEY }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
      run: |
        chmod +x run_updater.sh
        ./run_updater.sh
        
    - name: 💾 Сохранение логов
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: updater-logs
        path: "*.log"
        retention-days: 30
        
    - name: 📊 Отчет о статусе
      if: failure()
      run: |
        echo "❌ Обновление индекса завершилось с ошибкой"
        if [ -f "updater.log" ]; then
          echo "Последние строки лога:"
          tail -20 updater.log
        fi 